# Script for preparing images and calibration data 
#   for Yasutaka Furukawa's PMVS system

BUNDLER_BIN_PATH= # Edit this line before running
if [ "$BUNDLER_BIN_PATH" == "" ] ; then echo Please edit prep_pmvs.sh to specify the path to the  bundler binaries.; exit; fi
# Apply radial undistortion to the images
$BUNDLER_BIN_PATH/RadialUndistort /home/niclas/code/dronarch/project/roaming/bundler/all_imgs.txt /home/niclas/code/dronarch/project/roaming/bundler/bundle.out /home/niclas/code/dronarch/project/roaming/pmvs/

# Create directory structure
mkdir -p /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mkdir -p /home/niclas/code/dronarch/project/roaming/pmvs//visualize/
mkdir -p /home/niclas/code/dronarch/project/roaming/pmvs//models/

# Copy and rename files
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_0.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000000.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000000.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_1.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000001.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000001.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_2.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000002.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000002.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_3.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000003.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000003.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_4.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000004.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000004.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_5.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000005.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000005.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_6.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000006.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000006.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_7.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000007.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000007.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_8.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000008.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000008.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_9.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000009.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000009.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_10.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000010.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000010.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_11.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000011.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000011.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_12.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000012.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000012.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_13.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000013.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000013.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_14.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000014.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000014.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_15.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000015.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000015.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_16.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000016.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000016.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_17.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000017.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000017.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_18.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000018.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000018.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_19.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000019.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000019.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_20.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000020.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000020.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_21.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000021.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000021.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_22.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000022.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000022.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_23.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000023.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000023.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_24.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000024.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000024.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_25.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000025.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000025.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_27.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000026.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000026.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_28.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000027.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000027.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_29.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000028.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000028.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_30.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000029.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000029.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_31.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000030.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000030.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_32.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000031.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000031.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_33.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000032.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000032.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_34.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000033.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000033.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_35.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000034.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000034.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_36.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000035.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000035.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_37.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000036.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000036.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_38.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000037.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000037.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_39.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000038.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000038.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_40.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000039.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000039.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_41.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000040.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000040.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_42.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000041.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000041.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_43.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000042.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000042.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_44.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000043.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000043.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_45.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000044.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000044.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_46.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000045.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000045.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_47.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000046.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000046.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_48.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000047.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000047.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_49.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000048.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000048.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_50.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000049.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000049.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_51.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000050.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000050.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_53.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000051.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000051.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_54.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000052.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000052.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_55.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000053.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000053.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_56.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000054.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000054.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_57.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000055.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000055.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_58.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000056.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000056.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_59.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000057.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000057.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_60.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000058.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000058.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_61.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000059.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000059.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_62.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000060.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000060.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_63.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000061.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000061.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_64.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000062.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000062.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_65.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000063.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000063.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_66.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000064.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000064.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_67.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000065.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000065.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_68.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000066.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000066.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_69.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000067.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000067.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_70.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000068.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000068.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_71.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000069.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000069.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_72.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000070.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000070.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_73.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000071.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000071.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_75.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000072.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000072.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_76.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000073.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000073.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_77.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000074.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000074.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_78.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000075.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000075.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_79.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000076.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000076.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_80.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000077.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000077.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_81.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000078.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000078.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_82.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000079.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000079.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_83.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000080.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000080.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_84.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000081.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000081.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_85.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000082.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000082.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_86.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000083.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000083.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_87.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000084.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000084.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_88.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000085.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000085.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_89.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000086.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000086.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_90.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000087.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000087.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_91.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000088.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000088.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_92.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000089.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000089.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_93.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000090.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000090.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_94.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000091.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000091.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_95.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000092.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000092.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_96.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000093.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000093.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_97.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000094.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000094.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_98.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000095.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000095.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_99.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000096.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000096.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_100.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000097.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000097.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_101.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000098.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000098.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_102.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000099.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000099.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_103.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000100.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000100.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_104.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000101.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000101.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_105.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000102.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000102.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_106.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000103.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000103.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_107.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000104.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000104.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_108.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000105.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000105.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_109.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000106.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000106.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_110.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000107.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000107.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_111.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000108.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000108.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_112.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000109.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000109.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_113.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000110.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000110.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_114.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000111.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000111.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_115.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000112.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000112.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_116.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000113.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000113.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_117.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000114.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000114.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_118.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000115.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000115.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_119.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000116.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000116.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_120.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000117.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000117.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_121.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000118.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000118.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_122.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000119.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000119.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_123.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000120.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000120.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_124.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000121.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000121.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_125.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000122.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000122.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_127.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000123.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000123.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_128.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000124.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000124.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_129.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000125.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000125.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_130.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000126.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000126.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_131.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000127.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000127.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_132.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000128.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000128.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_133.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000129.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000129.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_196.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000130.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000130.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_197.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000131.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000131.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_198.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000132.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000132.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/
mv pmvs//home/niclas/code/dronarch/project/roaming/vid_imgs/test2_199.rd.jpg /home/niclas/code/dronarch/project/roaming/pmvs//visualize/00000133.jpg
mv /home/niclas/code/dronarch/project/roaming/pmvs//00000133.txt /home/niclas/code/dronarch/project/roaming/pmvs//txt/

echo "Running Bundle2Vis to generate vis.dat
"
$BUNDLER_BIN_PATH/Bundle2Vis /home/niclas/code/dronarch/project/roaming/pmvs//bundle.rd.out /home/niclas/code/dronarch/project/roaming/pmvs//vis.dat



echo @@ Sample command for running pmvs:
echo "   pmvs2 /home/niclas/code/dronarch/project/roaming/pmvs// pmvs_options.txt"
echo "    - or - "
echo "   use Dr. Yasutaka Furukawa's view clustering algorithm to generate a set of options files."
echo "       The clustering software is available at http://grail.cs.washington.edu/software/cmvs"
